### ISSUE TITLE
OpenCV 4.9.0 and 4.10.0

### ISSUE THREAD

**Issue by josephmangmang** [eddy-lau/OpenCV-Dynamic-Framework#1]
Hello can we update the pod version for OpenCV-Dynamic-Framework to use latest opencv? 
Thank you

**Comment by josephmangmang** [comment]
![Screenshot 2024-08-14 at 3 21 54 PM](https://github.com/user-attachments/assets/c3a0f97d-3fad-471c-a8f0-c2deff0c7682)


HI @eddy-lau , can we update the `OpenCV-Dynamic-Framework` to 4.9.0 and 4.10.0 opencv? I currently need the latest DNN patches.
Thank you.

**Comment by eddy-lau** [comment]
It is updated to 4.10.0

**Comment by josephmangmang** [comment]
Thank you so much
